package hello;

import hello.Model.Aluno;
import hello.Model.Disciplinas;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import hello.Model.Curso;
import org.springframework.web.bind.annotation.RestController;

@RestController    // This means that this class is a Controller
@CrossOrigin
@RequestMapping(path = "/demo") // This means URL's start with /demo (after Application path)
public class MainController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;
    @Autowired
    private CursoRepository cursoRepository;
    
    @Autowired
    private DisciplinasRepository disciplinasRepository;
    
    @CrossOrigin
    @GetMapping(path = "/add") // Map ONLY GET Requests
    public @ResponseBody
    String addNewUser(@RequestParam String curso,
            @RequestParam String email,
            @RequestParam String nome,
            @RequestParam String semestre,
            @RequestParam String telefone,
            @RequestParam String turno) {
        Aluno aluno = new Aluno();
        aluno.setCurso(curso);
        aluno.setEmail(email);
        aluno.setNome(nome);
        aluno.setSemestre(semestre);
        aluno.setTelefone(telefone);
        aluno.setTurno(turno);
        return "saved";
    }

    @GetMapping(path = "/all")
    public @ResponseBody
    Iterable<Aluno> getAllDisciplinases() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }    
    
    @GetMapping(path = "/curso")
    public @ResponseBody
    Iterable<Curso> getAllCurso(){
        return cursoRepository.findAll();
    }
    
    @GetMapping(path = "/disciplinas")
    public @ResponseBody
    Iterable<Disciplinas> getAllDisciplinas(){
        return disciplinasRepository.findAll();
    }
}
